### ISSUE TITLE
Wildcard Subdomain for user

### ISSUE THREAD

**Issue by elnappo** [nsupdate-info/nsupdate.info#133]
we could add a wildcard subdomain for users. For example:
*.elnappo.nsupdate.info 
so i could use www.elnappo.nsupdate.info, jabber.elnappo.nsupdate.info, ...

Your thoughts and ideas?

**Comment by JonasDaWi** [comment]
> if you want to have all ipv4 addrs to point to the same IP (== router IP), just use 0 as interface id.
@ThomasWaldmann it would be nice to add this to the documentation, because I only found this information here

**Comment by ThomasWaldmann** [comment]
Yeah, would be nice - can you do a PR?

**Comment by JonasDaWi** [comment]
Alright: #485
