### ISSUE TITLE
nsupdate.info site: timeouts when updating external nameserver

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#140]
updating an external ipv6 nameserver results in a timeout.

are packets being dropped by a firewall?

**Comment by puppeteerreplyhomepage** [comment]
10-plus.com	SOA	300		ip-172-26-1-31 hostmaster@power-dns.com

**Comment by puppeteerreplyhomepage** [comment]
Octopus.com
