### ISSUE TITLE
Custom domains hosting

### ISSUE THREAD

**Issue by leonaard** [nsupdate-info/nsupdate.info#145]
We should be able to add our own domain name and manage it directly in nsupdate-info.
Now we are only able to update another nameserver through nsupdate-info.

**Comment by ThomasWaldmann** [comment]
Note: this does not only need adding a new domain to the nameserver (that could be done automatically maybe), but also might need adding bind (nameserver specific) configuration, like:

* allow/deny rules what in the zone may be updated
* new key for dynamic updates of the zone

So, I fear this is getting a bit complicated / out of scope of the project (it's not a frontend to create nameserver-specific configuration) and thus I am closing this as "won't fix".

In general: if someone has a cool domain and wants to donate it for a longer period of time, we can always setup something manually on our DNS servers.
