### ISSUE TITLE
upgrade to jquery 2.x.x

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#178]
when we are ready to drop IE6/7/8 compatibility, we can upgrade to jquery 2.x.x.

From WP: "Support for Internet Explorer 8 is bound to the lifecycle of the Windows version it is installed on; as such, IE8 is no longer supported on Windows XP as of April 8, 2014". On all other OSes, Microsoftz will end IE8 security updates in Jan 2016.

Vista and newer OSes have IE9 and newer, one just needs to install it.

**Comment by elnappo** [comment]
I think the time is right, 0.12? ;)

**Comment by ThomasWaldmann** [comment]
maybe a bit later, 0.12 is already full of quite some other bigger changes.
also, we're not in a hurry here as long as jquery 1.x is supported / gets updates.

**Comment by elnappo** [comment]
IE 8, 9, 10 is EoL
https://support.microsoft.com/en-us/kb/3123303?sd=rss&spid=14019

**Comment by elnappo** [comment]
Upgrade to jQuery 3 directly?

**Comment by ThomasWaldmann** [comment]
https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support that's a better link (the other link is only about the notification).

But yes, obviously we can drop support for IE < 11.
