### ISSUE TITLE
add a slug field for domain and hosts

### ISSUE THREAD

**Issue by elnappo** [nsupdate-info/nsupdate.info#187]
e.g.: nsupdate.info/host/test-nsupdate-de/ instead of  nsupdate.info/host/1341/
This makes urls much more readable and don't expose host and domain ids
django-extensions already has a AutoSlugField or use https://bitbucket.org/neithere/django-autoslug/

**Comment by ThomasWaldmann** [comment]
looked at django-autoslug shortly. latest release seems to be behind repo quite a bit and repo has changes for django 1.7 support that are not released yet.
