### ISSUE TITLE
check if ipv6 is made by a stack with privacy extensions

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#199]
we show ipv4 and v6 addresses on the main page of the service.

we could add a small hint ("PE") if we detect that the v6 addr isn't derived from interface mac.

note: we can't know whether the whole address is static as the prefix might also change.

**Comment by elnappo** [comment]
There are more and more ways to generate stable interface (host part) addresses which are not using the MAC of the interface such as [RFC7217](https://tools.ietf.org/html/rfc7217). As far as I see, it is not possible to detect if a address was generated via RFC7217. So the proposal would leat to many false-positives.

**Comment by ThomasWaldmann** [comment]
closing, not reliably possible.

also: chosing and sending the right ipv6 addr is problem of the dyndns client.
