### ISSUE TITLE
DNS update error [PeerBadKey]

### ISSUE THREAD

**Issue by Mezhinsky** [nsupdate-info/nsupdate.info#204]
can't add host with whis error, on server has:tsig verify failure (BADKEY) but when use nsupdate zone adding normal, no matter from localhost or remote host please help

**Comment by ThomasWaldmann** [comment]
please describe more precisely what you are doing, I can't follow you.

**Comment by Mezhinsky** [comment]
the problem solved by adding key directly in zone sectionts of bind, not separatly

**Comment by ThomasWaldmann** [comment]
ah, good you found the reason. :)

**Comment by dmsherazi** [comment]
I am having the same error, @Mezhinsky  can you please explain where to add the key directly?
