### ISSUE TITLE
pfsense "result match"

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#207]
A user reported this about the example pfsense configuration we show after adding a new host:
"""
I use pfSense and had the "Result match" code copy-pasted to my pfSense configuration. However, in pfSense one must escape the vertical bar (i.e. |) with a backslash (i.e. \). I now added the "\" and believe all is well now.
"""
```
What we currently show is: Result match: good|nochg

What the user suggests is: Result match: good\|nochg
```
Can somebody please comment on what is correct? I personally don't use pfsense and can't test it.

**Comment by ThomasWaldmann** [comment]
as there was no feedback yet, I'll shift this to next milestone.

**Comment by lebeno** [comment]
I have the same error and performed some tests. Still no success.

pfSense System logs when updating:
`php-fpm[7041]: /services_dyndns_edit.php: phpDynDNS: (Error) Result did not match.`

I changed Result Match from `good\nochg` to `good\|nochg` but same result.

It looks like the dynamic update is registered at nsupdate.info, but the parsing of the result on pfSense fails.

**Comment by ThomasWaldmann** [comment]
Did you also try "good|nochg"?

BTW, nsupdate.info returns standard return strings as specified by the dyndns "standard", so it should be not too hard to configure pfsense for it (assuming that it works in principle).

**Comment by lebeno** [comment]
Yes, I tried `good|nochg` and same result. `good\nochg` was a typo in my comment.

**Comment by ThomasWaldmann** [comment]
maybe it tries to do a full match. the results looks like "good 1.2.3.4" or "nochg 1.2.3.4".

**Comment by lebeno** [comment]
Looks like it is indeed necessary to do a full match, the actual Result Match string that works is
`good %IP%|nochg %IP%`

Tested on pfSense 2.2.6-RELEASE. Got inspiration from this post: http://www.slicesofcomputer.com/2015/01/make-google-domains-dyndns-work-with.html

I suggest correcting the "Result String" in the pfSense section of nsupdate.info "How to configure automated dynamic DNS updates?".

**Comment by ThomasWaldmann** [comment]
TODO: add working string to the configuration help it shows after adding a host.

**Comment by FreeMinded** [comment]
Fixed with this commit https://github.com/nsupdate-info/nsupdate.info/pull/263
