### ISSUE TITLE
Add mx record to my host

### ISSUE THREAD

**Issue by somenxavier** [nsupdate-info/nsupdate.info#212]
Hi,

How can I add mx record for receiving and sending emails via MTA?
By the oher hand, can I buy a domain (like foo.com) and associate with my host? And put mx in that?

Thansks,

**Comment by ThomasWaldmann** [comment]
There is no support (yet) for any other record than A and AAAA. There is a ticket though for adding such support later, but it is currently noone actively working on this.

We don't sell domains.

What you can do with an outside domain is to put a CNAME record there and point it to your dynamic host, like:

foo.example.org CNAME yourhost.nsupdate.info

The left one will then resolve the the IP addresse of the right one.

**Comment by ThomasWaldmann** [comment]
See there for more comments on other record types / MX / etc:

https://github.com/nsupdate-info/nsupdate.info/issues/105

Closing this one as duplicate.

**Comment by somenxavier** [comment]
It's a pitty to hearing that. I planned to host my own web server and mail server in my home. I found this [solution](http://www.dyncommunity.com/questions/670/can-i-setup-mx-records-with-dyndns.html) for other dynamic hosting. Could I apply here?

On the other hand, if I buy a domain I will  not be able to have email MX too because I will redirect to foo.nsupdate.info but it will not have MX record. Is this reasoning correct?

Can you give me some clues of that? I'm completely ignorant of this topic.

Thanks,

**Comment by ThomasWaldmann** [comment]
About hosting your mail server at home, please see #105.

That "solution" you have linked does not help you as you currently can not set any MX record on nsupdate.info. And even if you could, see #105 about why it would not work sufficiently in the end anyway.

And yes, I think you suspect right, IIRC a CNAME is not allowed for an MX record, so the workaround for an A record of an external ("static") domain does not work for the MX record.

**Comment by somenxavier** [comment]
But dynu.com does [it](http://www.dynu.com/DynamicDNS/Features). Why? How? Why can't we do that?

**Comment by elnappo** [comment]
I would suggest to rent a cheap vps to host your own mail server. There available from 15$/y (http://lowendbox.com/). This could save you a lot of trouble.

**Comment by ThomasWaldmann** [comment]
@somenxavier there is no fundamental problem in supporting MX (or any other record) in dynamic dns.
Just the practical implications (like mail servers not accepting email from your "at home" MX) might not be as you like.

But: nsupdate.info does not have code yet to support anything else than A and AAAA, see #105.
