### ISSUE TITLE
related hosts: ipv6 interface-id too short (limited to max. 22 characters)

### ISSUE THREAD

**Issue by joachimneu** [nsupdate-info/nsupdate.info#221]
The length of the "ipv6 interface-id" field for related hosts is limited to max. 22 characters. While this is enough in the case of /64 subnets, in general it's too short. It technically works also for bigger subnets (which can be configured using the "netmask ipv6" field of a host), it's just that the user interface does not allow for long enough interface-ids.

**Comment by ThomasWaldmann** [comment]
fixed, see link above.

**Comment by joachimneu** [comment]
Great, thank you so much! Any indication when this fix will be deployed in production on nsupdate.info?

**Comment by joachimneu** [comment]
Great, seems to work now! Thank you!
