### ISSUE TITLE
put nsupdate.info onto public suffix list

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#224]
https://publicsuffix.org/
https://community.letsencrypt.org/t/dyndns-no-ip-managed-dns-support/883/11

check what cookies we use ourselves.

check whether this influences letsencrypt certificate issuance.

**Comment by ThomasWaldmann** [comment]
current state: we set 2 cookies for nsupdate.info: sessionid and csrftoken.

so we **first** need to migrate the main site to www.nsupdate.info, set the cookies there and **then** get onto that list.

**Comment by ThomasWaldmann** [comment]
https://github.com/publicsuffix/list/pull/93

looking at the list of all pull requests there, it seems this could take longer. please add any requests about when it will be added there to the pull requests linked above.

**Comment by elnappo** [comment]
https://github.com/publicsuffix/list/pull/100

**Comment by elnappo** [comment]
nsupdate.info and nerdpol.ovh is now on the list.

**Comment by ThomasWaldmann** [comment]
\o/

Now let's see how long it takes letsencrypt to use the latest list...

**Comment by ThomasWaldmann** [comment]
This is how the `_psl` txt records should look like:
```
_psl.nsupdate.info.	3600	IN	TXT	"https://github.com/publicsuffix/list/pull/93"
_psl.nerdpol.ovh.	3600	IN	TXT	"https://github.com/publicsuffix/list/pull/100"
```
