### ISSUE TITLE
related host: related AAAA-hosts should have an additional A-Record

### ISSUE THREAD

**Issue by hensing** [nsupdate-info/nsupdate.info#230]
An option to inherit the A record from the related host would be great, e.g., related.sub.example.com inherits the A-record from sub.example.com.

**Comment by ThomasWaldmann** [comment]
Nice feature if you port-forward base.dom:port -> host.base.dom:port, then you can just use host.base.dom with port and it works.

But: if you can't use the same port on base.dom (v4) as on host.base.dom (v6), you can not avoid connecting to the v4 address any more and you connect will only work in 50% of the cases.

**Comment by ThomasWaldmann** [comment]
Hmm, I guess this is already possible, just maybe not obvious:

Try setting the v4 interface id to 0.0.0.0 then you should get an A record that is main address + 0.0.0.0 == main address.

**Comment by hensing** [comment]
that's exactly what I was looking for
