### ISSUE TITLE
Openwrt config is wrong.

### ISSUE THREAD

**Issue by the-solipsist** [nsupdate-info/nsupdate.info#259]
In the Openwrt config, these are provided:

    option service_name "{{ WWW_HOST }}"
    option update_url "http://[USERNAME]:[PASSWORD]@{{ WWW_IPV4_HOST }}/nic/update?hostname=[DOMAIN]&myip=[IP]"

This doesn't work (at least in Chaos Calmer - git-15.248.30277-3836b45).  Only one of those two options should be used.  If both are used, it fails to update.  Since `option service_name` is not needed, remove that line:
https://github.com/nsupdate-info/nsupdate.info/blob/c4a93218a4581d10112069ddb2ab0a4a5dba778c/nsupdate/main/templates/main/includes/tabbed_router_configuration.html#L247

**Comment by ThomasWaldmann** [comment]
OK, thanks for the feedback.
