### ISSUE TITLE
Your current IP seen local host

### ISSUE THREAD

**Issue by dipenpatel235** [nsupdate-info/nsupdate.info#260]
Hello when i open "https://www.nsupdate.info/" link show it show my correct ip

i have setup my own nsupdate server and show my ip is 127.0.0.1. so what i have did wrong ?

Your current IP(s) + reverse DNS:

IPv4: 127.0.0.1

Thanks

**Comment by ThomasWaldmann** [comment]
That would be expected if server and client run on same machine.
Or if the server runs behing a http reverse proxy.

**Comment by dipenpatel235** [comment]
Ok...Thanks.
