### ISSUE TITLE
nginx Proxy Pass show localhost IP

### ISSUE THREAD

**Issue by dipenpatel235** [nsupdate-info/nsupdate.info#264]
Hello...
i am doing proxy pass from nginx to nsupdate port
so on front page it is displayed 127.0.0.1

instead of that i want to displayed real IP.
So how can i real ip ?

I have also try using  
        proxy_set_header        X-Real-IP       $remote_addr;
But not success

Thanks

**Comment by dipenpatel235** [comment]
Thanks
I Have Fixed this issue By Below Patch
So May Be SOme one useful

I Have Used nginx with reverse proxy with real ip

Then In nsupdate info in all file replace REMOTE_ADDR By HTTP_X_REAL_IP

sed -i 's/REMOTE_ADDR/HTTP_X_REAL_IP/g'  filename

Thanks

**Comment by ThomasWaldmann** [comment]
On nsupdate.info, the software runs behind a nginx proxy without changing of any of its files.

**Comment by elnappo** [comment]
close? maybe add a nginx config example (could also be useful for #281) https://nsupdateinfo.readthedocs.io/en/latest/admin.html#installation-for-production
