### ISSUE TITLE
implement mail domain blacklist

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#284]
recently, I regularly get error mails from postfix because somebody registered with an email address of a non-functional mail domain.

such domains could end up on a blacklist and account registration could be rejected for them.

**Comment by ThomasWaldmann** [comment]
it could be also like a regular check: if a user account has an email address/domain on the blacklist, it will trigger a similar "get rid of this" mechanism as when you don't use a host for a long time.

i get tons of mailer daemon spam meanwhile due to people using non-working email addresses.

**Comment by elnappo** [comment]
https://github.com/aaronbassett/DisposableEmailChecker

**Comment by ThomasWaldmann** [comment]
related: #375
