### ISSUE TITLE
gentoo & startssl troubles, use letsencrypt certificate

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#285]
I got notified that gentoo removed the root cert of startssl, making TLS connections to nsupdate.info fail.

We should use letsencrypt certificates.

**Comment by ThomasWaldmann** [comment]
It's planned to move nsupdate.info service to a new server, but the precise date is unknown yet.

On that server, we'll also use letsencrypt certificates for nsupdate.info, if possible.

About gentoo's timing: it is known that startssl/wosign is on the way out, but until today I thought there is a gradual deprecation, first hitting all NEW certs (does not apply for us), then also the expiring certs (next year for us). So, gentoo was maybe a bit too quick / radical with this.

Workarounds for gentoo users might be:
- install startssl root cert manually
- using http to update IP

**Comment by bonki** [comment]
Thanks for posting, we can continue this here :)

More specifically, it's `ca-certificates-20160104.3.27.1-r2` which removed the StartCom and WoSign CAs from Gentoo unstable (bug [#598072](https://bugs.gentoo.org/show_bug.cgi?id=598072)). The `USE` flag `insecure_certs` allows for them to be installed for now, i.e. if you trust the CAs something along the lines of

    # echo "app-misc/ca-certificates insecure_certs" >/etc/portage/package.use/insecure-certs
    # emerge ca-certificates

reinstalls all certificates and temporarily "fixes" the problem.

I agree that this was a hasty decision to make. Google and Mozilla provide more information on the matter and describe the actions they are taking [here](https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html) and [here](https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/).

There is one paragraph (quoting Google) I don't really understand, though (emphasis mine):

> Due to a number of technical limitations and concerns, Google Chrome is unable to trust **all** pre-existing certificates while ensuring our users are sufficiently protected from further misissuance. As a result of these changes, customers of WoSign and StartCom may find their certificates no longer work in Chrome 56.

The way I read it this means that even certificates issued *before* cut-off date (October 21, 2016) might be subject to not being trusted in Chrome 56 any longer.

Obviously, I'd rather see us transition sooner than later.

**Comment by ThomasWaldmann** [comment]
I just switched https://nsupdate.info/ service to a Let's Encrypt certificate, thus the cert problem is solved.

The server move is still pending, but will also happen soon.

**Comment by ThomasWaldmann** [comment]
As I side note:

We could not offer donations while using StartSSL for-free certificate.

Thus I reenabled donations now, see the site footer.
