### ISSUE TITLE
add speedport hybrid example configuration?

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#286]
From my inbox:

Add under "Show Configuration" this example:
``` 
Speedport Hybrid configuration:
(Firmware 050124.03.00.012)
 
Domänenname: fkjdbnsfjsd.nerdpol.ovh
 
Benutzername: fkjdbnsfjsd.nerdpol.ovh
 
Kennwort: here you must enter the "Secret" you get under "Show Configuration"
 
Updateserver-Adresse: https://ipv4.nsupdate.info
Protokoll HTTPS
Port 443
```

**Comment by ThomasWaldmann** [comment]
Not sure how popular this kind of router is, can anybody comment?

**Comment by elnappo** [comment]
Would be interesting to know if this interface is the same on all speedport routers. These routers are mainly used by Deutsche Telekom (German Telecom).

**Comment by maboxx** [comment]
I recently use this router and will now test it as described above. If I have any problems with that, I will report here. What I notice in the first moment. I have entered and saved the data but in my nsupdate.info account there is currently no refresh of the IP4v address. I'm will watch if it work on the next ip switch.

**Comment by maboxx** [comment]
OK, the router IP address has change but but the nsupdate.info account do not received an update.

Domänenname = name.nsupdate.info
Benutzername = name.nsupdate.info
Kennwort = xxxxxxxx
Updateserver-Adresse = https://ipv4.nsupdate.info/nic/update
Protokoll = https
Port = 44

**Comment by ThomasWaldmann** [comment]
There seems some duplication...

Port 443

If they ask for the protocol separately, it might be the case that they only want ipv4.nsupdate.info/nic/update (not https:// here) for the update server address.

**Comment by maboxx** [comment]
OK I test it again and it didn't work, even without "https" it doesn't work (just with ipv4.nsupdate.info/nic/update)

**Comment by maboxx** [comment]
In the event log of the speeport hyprid I can see the following entry:

> (D001) Aktualisierung für Dynamic DNS war nicht erfolgreich. Der Update Server konnte nicht erreicht werden.

When I type the URL https://ipv4.nsupdate.info/nic/update into the browser and login I receive the following:

> https://ipv4.nsupdate.info/nic/update

**Comment by ThomasWaldmann** [comment]
notfqdn means that the hostname you gave is not a fully qualified domain name.

e.g. foo instead of foo.nsupdate.info

**Comment by maboxx** [comment]
Ok I give up.
It doesn`t work with a Hyprid Speedport. As you can see above my configuration:

Domänenname = name.nsupdate.info
Benutzername = name.nsupdate.info
Kennwort = xxxxxxxx
Updateserver-Adresse = https://ipv4.nsupdate.info/nic/update
Protokoll = https
Port = 443

I always receive the message:
`(D001) Aktualisierung für Dynamic DNS war nicht erfolgreich. Der Update Server konnte nicht erreicht werden.`
Even if I remove https at the server address.

**Comment by ThomasWaldmann** [comment]
Maybe they have bugs in processing these values (see my comment about duplication).

Ehrm, I just noticed there is no "path" in the URL in the top post. Can you try that?:

Updateserver-Adresse: https://ipv4.nsupdate.info

**Comment by ThomasWaldmann** [comment]
@maboxx glad it worked now. Can you tell us the firmware version of your router?

**Comment by maboxx** [comment]
Router: **Speedport Hybrid**
Firmware version: **050124.03.07.001**

Thank you so much for your great service on nusupdate.info

**Comment by maboxx** [comment]
Ok I switch the GUI to english, here is the post with text in english:
......
Great, it works like this:

Provider = other Provider
Domain name = name.nsupdate.info
User name = name.nsupdate.info
Password = secret for that host
Updateserver-Adresse = https://ipv4.nsupdate.info
Protokoll = https
Port = 443

The problem was the password. I used the password for the login on my account on nsupdate.info.
I probably should have read your first post better, sorry.

**Comment by marcusgrtz** [comment]
Does anyone know what the settings are for a Speedport Smart 4 router?

**Comment by strarsis** [comment]
@marcusgrtz: When the Speedport Smart 4 router has an internet connection with IPv6 and IPv4, it will send both IP addresses comma-separated for a single parameter. This is incompatible with most custom/free DynDNS-providers, except for IPv64.net.

You can use a HTTP request catcher as the updater URL (e.g. https://webhook.site/) to see what the Speedport actually sends (including HTTP auth and IP value).
