### ISSUE TITLE
Instructions for ASUS Routers running Merlin?

### ISSUE THREAD

**Issue by porcupinepete** [nsupdate-info/nsupdate.info#288]
Just wondering if there is any plan to add instructions/ script for ASUS routers running Merlin. (As I'd love to use this service but have no idea what to do.)

Thanks.

**Comment by ThomasWaldmann** [comment]
I don't have a Asus router, but maybe someone else can help here.

In general, if you read the general informations tab given to you after having added a host, you should be able to get all infos needed for setting up an update client (in your router).

Where to enter this in your router configuration UI you have to find out. You will need sort of a "custom" dyndns entry form, hardcoded entries don't help here if they do not include nsupdate.info service.

**Comment by elnappo** [comment]
@porcupinepete could you provide a screenshot of your routers dyndns configuration page? It looks like these routers are using a OpenWRT based firmware (AsusWRT). So configuration should be similar to OpenWRT?

**Comment by ThomasWaldmann** [comment]
no reply...
