### ISSUE TITLE
better financial support for the project

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#294]
nsupdate.info uses bountysource to enable its users to support the project by donations and bounties.

https://www.bountysource.com/teams/nsupdate-info

General funds donated to the project will be used for putting bounties onto important issues and the developer resolving the issue will get the bounty.

One can also donate money for solving a specific issue by creating a bounty for that github issue.

**Comment by elnappo** [comment]
Enable GitHub sponsorships?

**Comment by ThomasWaldmann** [comment]
See sponsor link at top of github page.
