### ISSUE TITLE
Use external ip check - change wording on #dd-wrt instructions

### ISSUE THREAD

**Issue by 2SI3NX** [nsupdate-info/nsupdate.info#300]
where you have:
How to configure automated dynamic DNS updates?
under #DD-WRT
Instead of "Do not use external ip check	- Yes"
Its better to use:
**Use external ip check  Yes/No**
on the latest dd-wrt firmware thats how it is.

It gets confusing when there is yes/no and saying the exact opposite in the instructions.
Can you update that and make it:
**Use external ip check  No**
thanks

**Comment by ThomasWaldmann** [comment]
@2SI3NX we like to tell for which versions our configurations apply.

so, for which dd-wrt version is the change you are requesting?

also, for that version, are the other instructions still correct?

**Comment by 2SI3NX** [comment]
@ThomasWaldmann The firmware is for the latest ftp://ftp.dd-wrt.com/betas/2017/

At the moment i havent seen any other instructions being different. Its only the one i mentioned which is quite vague in the instructions.

**Comment by ThomasWaldmann** [comment]
Hmm, if it is beta still, we maybe don't want to reflect changes that appeared in the beta in our docs / generated config files.

So, can you check whether the setting is also as you propose in the latest release?

**Comment by 2SI3NX** [comment]
Well, they **say** its Beta, but really if you look up one directory: ftp://ftp.dd-wrt.com/betas/
Those years are mostly all stable versions even though they say they are betas. They are the latest and mostly stable. If you go back again one directory and you go to stable, the latest stable is in 2008 which is unreliable.

Everyone who has dd-wrt and wants the latest, they download from the beta's section.

Currently this setting im proposing is on the latest version and actually all versions in 2016 as ive been updating.

**Comment by ThomasWaldmann** [comment]
sigh. would be great if they had sane release management.

ok, I'll update as you proposed before next release of nsupdate.info.
