### ISSUE TITLE
Differentiate between show configuration and create new configuration/password

### ISSUE THREAD

**Issue by tobiasstein** [nsupdate-info/nsupdate.info#303]
**Please** change the default behavior of the "Show Configuration" button inside of a configured host,
to not generate a new secret and introduce a new button to generate a new secret.

Restoring the old password in the database (triggering the python code) is not a common task for every body and requires to memorize the secret. If there is no possibility to access and change a client's password remotely, administrators have to visit the site and configure the device directly, which generally leads to some overhead. :-)

👍

**Comment by ThomasWaldmann** [comment]
So, how would you generate a config (which includes the password) without generating a new password?

We can't show the old password as we do not store the password in plaintext.

**Comment by ThomasWaldmann** [comment]
@tobiasstein did you read my comment?

I am open to ideas, but I think showing a complete configuration without creating a new password is not possible without violating security best practices.

Also, showing a configuration should only be needed if you currently (re)configure a device or a software.
