### ISSUE TITLE
inadyn 2.1 valid config

### ISSUE THREAD

**Issue by enricostano** [nsupdate-info/nsupdate.info#304]
Since latest versions a valid configuration should be like the following:
```
# /etc/inadyn.conf

period       = 300

provider ipv4@nsupdate.info {
    ssl      = true
    username = myhost.nsupdate.info
    password = mypassword
    hostname = myhost.nsupdate.info
}
```
Please point me to the right place if I can change this directly opening a PR. Thanks!

**Comment by elnappo** [comment]
https://github.com/nsupdate-info/nsupdate.info/blob/master/nsupdate/main/templates/main/includes/tabbed_router_configuration.html
