### ISSUE TITLE
Travis CI Django version declaration has no effect

### ISSUE THREAD

**Issue by elnappo** [nsupdate-info/nsupdate.info#314]
Its get overwritten by https://github.com/nsupdate-info/nsupdate.info/blob/master/scripts/travis/install.sh#L23

**Comment by ThomasWaldmann** [comment]
not sure what you are saying here.

the line you point to is requirements.d/travis.txt, but there is no "django" in there, just other stuff.

**Comment by elnappo** [comment]
fixed in #313
