### ISSUE TITLE
SSL certificate expiration on nsupdate.info ??

### ISSUE THREAD

**Issue by 2SI3NX** [nsupdate-info/nsupdate.info#316]
I noticed trying to access nsupdate.info it throws cert error, im sure you are aware of this?
I tried adding to exceptions through firefox but still doesnt let me in

**Comment by ThomasWaldmann** [comment]
cert expired some h ago, I'll install a new one. thanks for the hint.

**Comment by 2SI3NX** [comment]
thanks. just a q, is this also why the clients such as ddclient arent updating?

**Comment by ThomasWaldmann** [comment]
if they use https (and check the cert): maybe.

**Comment by ThomasWaldmann** [comment]
fixed. :)

**Comment by PowerInside** [comment]
Expired again I guess! Getting invalid cert date error.

**Comment by 2SI3NX** [comment]
same.  Haven't you set Let'sEncrypt as a cron job for renewal every 3 months?

**Comment by ThomasWaldmann** [comment]
fixed. there is a LE cron job, but it's on another host (where we want to move the service to, but that has not happened yet).
