### ISSUE TITLE
Allow also CNAME records

### ISSUE THREAD

**Issue by wienand** [nsupdate-info/nsupdate.info#321]
It would be nice to also allow the creation of [CNAME records](https://en.wikipedia.org/wiki/CNAME_record).

One use case are standalone web application on [GitHub with custom domain names](https://help.github.com/articles/using-a-custom-domain-with-github-pages/). You could then serve several different applications without having them shared their local storage and non-IT users find it easier to access applications by just a domain name.

**Comment by ThomasWaldmann** [comment]
I think there is also a more general older ticket about "other than just A/AAAA records".

**Comment by wienand** [comment]
I found it. Just searched for CNAME on the open tickets and found nothing.

duplicate / subset of #105.
