### ISSUE TITLE
Apple AirPort "Use dynamic global hostname" support?

### ISSUE THREAD

**Issue by duffyjp** [nsupdate-info/nsupdate.info#322]
![screen shot 2017-12-07 at 3 25 03 am](https://user-images.githubusercontent.com/382216/33707801-491b8382-dafe-11e7-9d4c-8760aa88c654.png)

I'm running an Apple Airport Extreme, and if I'm wondering if this should be working.  There is absolutely no status report that I can find in the router setup, and I'm not getting a refresh shown on my Overview -> Result Messages.  My last update from ddclient was pretty recent though.  I turned ddclient off, I figure if the router can do it that's the way to go.

https://support.apple.com/kb/PH25641?viewlocale=en_US&locale=en_US

**Comment by ThomasWaldmann** [comment]
RFC 3007 is about dynamic DNS updates sending to a DNS server via the DNS protocol (not: to a dyndns-like service via http protocol), so this does not match.

If ddclient worked for you, just continue using that. Even if the router supports the correct dyndns protocol, running ddclient on some internal host is often more reliable than the router's dyndns code.
