### ISSUE TITLE
option for adding NS record?

### ISSUE THREAD

**Issue by gr01d** [nsupdate-info/nsupdate.info#323]
So I am trying to setup an iodine dns tunnel and I cannot find any option for adding an NS record. Is this even possible?

**Comment by ThomasWaldmann** [comment]
It is not yet supported to add any records besides A and AAA.
IIRC we have a ticket about adding such records, but it is not currently being worked on.

**Comment by ThomasWaldmann** [comment]
duplicate of #105.
