### ISSUE TITLE
travis ci testing is currently completely broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#325]
https://travis-ci.org/nsupdate-info/nsupdate.info/builds/329198061

**Comment by elnappo** [comment]
should be fixed when #313 is merged, maybe this week.

**Comment by nougad** [comment]
Any update on the pr? Currently not only travis is broken but registration in general. The PR fixes registration.

**Comment by ThomasWaldmann** [comment]
@nougad so, are you saying you are already practically run the PR's code for a dynds service based on nsupdate.info?

I just did review it (again) and only found some minor issues, guess we can merge it soon.

**Comment by elnappo** [comment]
Sorry, I try to make the pr ready today!

**Comment by elnappo** [comment]
fixed in #313
