### ISSUE TITLE
I18n arabic

### ISSUE THREAD

**Issue by ghost** [nsupdate-info/nsupdate.info#327]
Hi,
Strings are being translated to Arabic on : https://www.transifex.com/opendz/nsupdateinfo-1/

I'll try to deliver it this week. Be ready for RTL.
Best regard,

**Comment by ThomasWaldmann** [comment]
@BoFFire thanks for working on this!

**Comment by BoFFire** [comment]
👍

**Comment by ThomasWaldmann** [comment]
URL is 404.
