### ISSUE TITLE
Update gives dnserr

### ISSUE THREAD

**Issue by franzhartwig** [nsupdate-info/nsupdate.info#328]
Hi,

using dnsupdate.info for years, now. My AVM Fritzbox reconnects every night and updates dnsupdate.info. Since today, I get an dnserr. Even if I try to update with your Web GUI, this error occurs. What is going wrong, what does dnserr mean?

**Comment by franzhartwig** [comment]
Update: Problem seems to be solved. Updating via Web GUI and via AVM Fritzbox works now.

**Comment by ThomasWaldmann** [comment]
The whole hw server was down, sorry. :(
