### ISSUE TITLE
password reset and new account; no email

### ISSUE THREAD

**Issue by luckymedog** [nsupdate-info/nsupdate.info#329]
I forgot my password (changed it not too long ago). Your system states that password reset instructions sent to my email, but I've not received anything. Have tried several times.

I've tried to create new account, but no activation email received either. 

I've sent email about issue from, but no response.

**Comment by ThomasWaldmann** [comment]
Do you have a gmail mail address? Their server rejects our mails (sometimes?).

**Comment by luckymedog** [comment]
Finally received emails. Thanks for response.

**Comment by yoander** [comment]
> Finally received emails. Thanks for response.

I'm experiencing this issue, do you received in your gmail?

**Comment by ThomasWaldmann** [comment]
The usual cause if one does not receive a mail from nsupdate.info is because the receiving mailserver rejects our emails (e.g. because it thinks it is spam, for whatever reason).
