### ISSUE TITLE
git rid of zombie users

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#330]
on nsupdate.info, there are quite a big amount of users who last logged in more than 2y ago.

i guess we can assume that quite some of these do not use nsupdate.info any more (or even never really used it).

i guess we could delete a user account if:
- there was no login for more than 1y
- and there are no hosts linked to that user (we already have a mechanism that gets rid of unused hosts)
- and there are no domains linked to that user (see #342)

**Comment by bonki** [comment]
I'm in favour of this. If you want to be extra nice you could mail all affected users (those whose profile includes an email address, anyway) and inform them first.

**Comment by ThomasWaldmann** [comment]
The problem with mailing (in general) is that quite a lot of users enter some crap email address.

When the service sends a mail to such an email address, an error occurs (no MX, no mailbox, mailbox full, ...) and postfix' mailer daemon message ends up in my mailbox. For the kind of user affected by the functionality discussed in this ticket, I assume that the percentage of crap accounts is even higher than for the more active accounts, so I suspect that I'ld get flooded with error messages. Not great.

**Comment by bonki** [comment]
That's why no-reply addresses exist? Dump incoming mails to that address into the æther or just use an Email as a Service-provider to send such mass-mail and let them deal with potential returning crap so you don't have to deal with it.
