### ISSUE TITLE
Failed to renew let's encrypt certificate: SERVFAIL looking up CAA 

### ISSUE THREAD

**Issue by githubtefo** [nsupdate-info/nsupdate.info#331]
My domain is: https://mydomain.awsmppl.com

I ran this command to renew my certificate:
certbot renew
or
certbot certonly --webroot -w /var/lib/letsencrypt/ -d mydomain.awsmppl.com (ArchWiki)

It produced this output:

    Domain: mydomain.awsmppl.com
    Type: connection
    Detail: DNS problem: SERVFAIL looking up CAA for mydomain.awsmppl.com

    To fix these errors, please make sure that your domain name was
    entered correctly and the DNS A/AAAA record(s) for that domain
    contain(s) the right IP address. Additionally, please check that
    your computer has a publicly routable IP address and that no
    firewalls are preventing the server from communicating with the
    client. If you’re using the webroot plugin, you should also verify
    that you are serving files from the webroot path you provided.

My web server is (include version): Apache
The operating system my web server runs on is (include version): Archlinux 32bits
My hosting provider, if applicable, is: self-hosted
I can login to a root shell on my machine (yes or no, or I don’t know): yes

Thank you!
My certificate will expire in 7 days and I really need my server for my work.

Might be related with the DNSSEC config?

reference issue: https://community.letsencrypt.org/t/renew-failed-servfail-looking-up-caa/57681

**Comment by ThomasWaldmann** [comment]
Note: I have notified the dns zone admin about this.

**Comment by TheGr8Wonder** [comment]
The zone has been rectified and the underlying issue that caused the invalid NSEC should be fixed as well. Additional monitoring has been added.

**Comment by githubtefo** [comment]
Thanks so much.
I will try again tonight and I will let you know.
Whank you again!

**Comment by githubtefo** [comment]
Succeeded!

**Comment by pharpe** [comment]
I'm having this exact same issue.
Running this command:
./certbot-auto certonly --standalone --standalone-supported-challenges http-01 --email myemail@gmail.com -d mydomain.awsmppl.com

Result:
Failed authorization procedure. mydomain.awsmppl.com (http-01): urn:acme:error:dns :: DNS problem: SERVFAIL looking up CAA for mydomain.awsmppl.com

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: pharpe.awsmppl.com
   Type:   None
   Detail: DNS problem: SERVFAIL looking up CAA for mydomain.awsmppl.com

**Comment by githubtefo** [comment]
In my case the issue disappeared. Moreover, the cron job worked great this month.

**Comment by githubtefo** [comment]
Same problem again!
Thanks for your help.-

**Comment by TheGr8Wonder** [comment]
May you try again now?

**Comment by githubtefo** [comment]
Now it works!
Great, thank you so much.

**Comment by githubtefo** [comment]
Hi everyone,

could you please double check/notify the dns zone admin about this again? It is not working and my certificate has expired yesterday :(

Thank you very much in advance!

**Comment by githubtefo** [comment]
Hi guys,

Any updates with this issue? I really appreciate your help to get my server up and running again.

Thank you!

**Comment by ThomasWaldmann** [comment]
@TheGr8Wonder ^^^

**Comment by githubtefo** [comment]
@TheGr8Wonder rectified the zone and the issue was solved!
I could renew my certificate now and the server is up and running again.
I really appreciate your help.
Thank y'all!
