### ISSUE TITLE
Major security issue with nerdpol.ovh - Urgent!

### ISSUE THREAD

**Issue by 2SI3NX** [nsupdate-info/nsupdate.info#332]
if you go to the nerdpol.ovh site itself, your browser gives a "deceptive site" warning and additionally is not allowed to be used with LetsEncrypt certificates.

Any idea whats going on and if the domain site is infected?
Please inform the owner asap.

**Comment by elnappo** [comment]
I'm the owner of nerdpol.ovh. I'm aware of the problem, sadly some people are trying to use subdomains under nerdpol.ovh for distributing malware and spam. As soon as we are aware of any abusive usage of hosts on nsupdate.info we blackhole them and close the issued user account. As for browser warnings, I'm regularly request review of the domain nerdpol.ovh in the Google Search Console to remove the warning.

Sorry for your trouble! I'll try to get the warning removed asap.

Related issues:
* https://github.com/nsupdate-info/nsupdate.info/issues/284
* https://github.com/nsupdate-info/nsupdate.info/issues/284
* https://github.com/nsupdate-info/nsupdate.info/issues/31

**Comment by 2SI3NX** [comment]
Appreciate your feedback! please let us know when this is sorted. thanks

**Comment by ThomasWaldmann** [comment]
BTW, this is the wrong place to deal with that.

That malware warning implementation is just wrong, you should complain to google/mozilla about it.

**Comment by 2SI3NX** [comment]
Well, elnappo stated that there are a lot of abusers and malware distributors that are abusing the domain hence why its been reported on google as a bad site in the first place which in turn causes cert issues.
Im not sure if google reports sites with malware for no reason.

**Comment by ThomasWaldmann** [comment]
@2SI3NX what do you think would the org domain registry do if someone reported that there is malware on malware-idiots.org?

**Comment by 2SI3NX** [comment]
@ThomasWaldmann Theres a big difference between a domain and a sub-domain in terms of who is responsible for issues, as there can be eg. 4 malware idiots with sub-domains causing a global problem for everyone else on that main domain.
To add to your example, the .org registry couldnt give 2 shits what people do with a domain(malware-idiots.org). Whereas an owner of a domain allowing other people to piggy-back on it to create sub-domains infested with malware has more a responsibility in finding the specific infection and killing it entirely (as elnappo said).

Complaining to Google is pointless, they don't care who has malware and they will take their sweet time to de-list it from the blacklist.  All they do is use a program to scan sites and auto-blacklist the full domain which can take ages to de-list (hopefully it doesnt)
Evidently, I felt it was my responsibility to report the actual problem on here anyway so that elnappo can take some kind of action against this or so that we can find a way (as you have come up with ideas in #284 & #31) to mitigate these problems.

**Comment by ThomasWaldmann** [comment]
I see it as basically the same problem on another level. And btw, we do not do anything on the base domain, it is all on www. / ipv4. / ipv6. hosts.

There are criminals and idiots on this planet and we can't change that. Even if we kick the criminals and all their hosts, who holds them back from registering new users and the same or other hosts a minute later on either our service or just another dyndns service?

And just because of that, I think the google mechanism of concluding when a.b.c is bad, so b.c and *.b.c must be bad also is fundamentally flawed.

**Comment by elnappo** [comment]
Review was approved yesterday afternoon. Flag is removed.
