### ISSUE TITLE
Starthilfe benötigt!

### ISSUE THREAD

**Issue by jottschi** [nsupdate-info/nsupdate.info#354]
Hi, kann einer der Listenlesenden mal kurz skizzieren, wie man 
nginx mit wsgi und den nsupdate.info-Python-Code zum Schwingen bekommt?
Der Hinweis in der Doku führt ins nirwana bzw in den Djungel der 1000 Möglichkeiten.
Vielen Dank!

**Comment by ThomasWaldmann** [comment]
einfach mal nach "nginx wsgi" im internet recherchieren und ein helloworld.wsgi zum laufen bringen?

danach sollte es dann auch mit nsupdate.info einfach gehen, ansonsten nochmal melden.
