### ISSUE TITLE
disable social login

### ISSUE THREAD

**Issue by smindorf** [nsupdate-info/nsupdate.info#376]
Hi all,

how can I disable all social logins?

Kind regards,
Sören

**Comment by ThomasWaldmann** [comment]
Not sure what you are asking about.

Are you asking from a user perspective, who create a log in to https://nsupdate.info/ or from an admin perspective, who does not want to offer social logins (from the beginning, or after initially offering them)?

**Comment by smindorf** [comment]
Hi, 
I'm looking from the admin site and I'll now allow social logins, so that they will not be offered.
Both is possible (from beginning and after initail and no one has registered).

Kind regards,
Sören

**Comment by ThomasWaldmann** [comment]
Switching off social login after people have registered and are using it might lead to users being unable to log in (if they had no local login). So be careful not to lock out users.

For most social logins, you need to configure/enable them in the config - the ones you do not configur/enable won't be offered.

We use these packages, they have own docs about how to configure them:
```
social-auth-app-django
social-auth-core
```
