### ISSUE TITLE
require Django 2.2 (LTS) and Python 3.x

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#386]
See also #379. We can remove all Python 2.x compatibility code.

As stopping support for Django 1.x and Python 2.x is a major change, we need to do this in a major release also, so this will be in nsupdate.info 1.0.0.

**Comment by ThomasWaldmann** [comment]
At the same time, we can also drop support for python 3.4.
Even Debian stable has already Python 3.5 now.

**Comment by ThomasWaldmann** [comment]
Django 2.2 is released now!

**Comment by ThomasWaldmann** [comment]
Now we have Django 3.0.

**Comment by elnappo** [comment]
fixed in https://github.com/nsupdate-info/nsupdate.info/commit/bf2a06353d74e5f26694b5f4758209faef60847c
