### ISSUE TITLE
Suggest inclusion to public suffixes list

### ISSUE THREAD

**Issue by Snawoot** [nsupdate-info/nsupdate.info#388]
Some major DNS providers ban public domains registered in nsupdate because of spammers.

There is a way to reduce impact: if parent domain will be added into [public suffix list](https://publicsuffix.org/), all subdomains shall be considered as owned by distinct administrators and bans will be more granular. Also, inclusion into public suffix list is essential for cookie security: in this case browsers will isolate domains properly.

Other dynamic DNS services actually include their domains into this list:
```
user@pc:~$ curl -s https://publicsuffix.org/list/public_suffix_list.dat | fgrep dyndns
// DynDNS.com : http://www.dyndns.com/services/dns/dyndns/
dyndns-at-home.com
dyndns-at-work.com
dyndns-blog.com
dyndns-free.com
dyndns-home.com
dyndns-ip.com
dyndns-mail.com
dyndns-office.com
dyndns-pics.com
dyndns-remote.com
dyndns-server.com
dyndns-web.com
dyndns-wiki.com
dyndns-work.com
dyndns.biz
dyndns.info
dyndns.org
dyndns.tv
dyndns.ws
go.dyndns.org
home.dyndns.org
dyndns.ddnss.de
dyndns1.de
```

Since only owner of domain may include it into public suffixes list, your service can only suggest owners to do that. I think some hint to domain owners will be useful (or even may be enforced as requirement for new public domains).

**Comment by ThomasWaldmann** [comment]
our domains are on that list, since about a year or so.
we can't add 3rd party domains, you need to contact their owner.

**Comment by ThomasWaldmann** [comment]
TODO: add a hint to "add domain" form.
