### ISSUE TITLE
drop python 3.4

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#406]
considering that some python tools (iirc setuptools, pytest) drop support for this soon, guess we better also drop support for it.

should be no big issue, even debian stable has 3.5.

**Comment by elnappo** [comment]
Django 2.2 also requires Python 3.5

**Comment by ThomasWaldmann** [comment]
Yeah, so later we'll drop it anyway.

The point of this ticket was to even drop it while we still support Django 1.11.

**Comment by ThomasWaldmann** [comment]
Just checked: nsupdate.info production instance runs on py35, so I'll drop py34 now before we run into issues with any dependencies or test tools.
