### ISSUE TITLE
filling the log with /favicon.{ico,png} 404

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#417]
seeing multiple log entries from same IP at same time requesting these resulting in a 404.

check if we link to that URL somewhere or if it is implicit like old browsers did.

handle the URL, so no 404 is logged.

**Comment by elnappo** [comment]
Browsers are requesting these files per default, with our new logo we should add a favicon :)

**Comment by ThomasWaldmann** [comment]
we do:
```
        <link rel="icon" type="image/png" href="/static/favicon.png" />
```

**Comment by elnappo** [comment]
It seems like not all browsers are respecting this property. I also see `/favicon.ico` requests in logfiles while providing a link to `/favicon.svg`. I guess adding a `/favicon.ico` should "fix" this problem.

**Comment by ThomasWaldmann** [comment]
did an alias on nginx level, so the requests don't get through to the wsgi app.
