### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ErAzOr2k** [nsupdate-info/nsupdate.info#434]
Hi,

what happened to nsupdate.info?
I just get "502 Bad Gateway".

Regards

**Comment by el0hh** [comment]
Hi, same problem.

**Comment by ThomasWaldmann** [comment]
nsupdate hat im Internet-Kurort Bad Gateway sich etwas erholt. :-)

(uwsgi somehow had segfaulted)
