### ISSUE TITLE
Domain awsmppl.com is considered a Deceptive site.

### ISSUE THREAD

**Issue by githubtefo** [nsupdate-info/nsupdate.info#437]
Hello,

Since yesterday, my subdomain (and apparently all //*.awsmppl.com) was marked as a Deceptive Site by Google.
I already informed to Google that my subdomain is safe, but is there anything else we/you the admins can do?

Thank you in advance.

**Comment by ThomasWaldmann** [comment]
If you have a problem with google, you need to talk with their support.

awsmppl.com is not even a domain of mine, but a "contributed" domain by another user.

I can forward a link to this issue to the domain owner, though.

**Comment by ThomasWaldmann** [comment]
See also #388.

**Comment by githubtefo** [comment]
> If you have a problem with google, you need to talk with their support.
> 
> awsmppl.com is not even a domain of mine, but a "contributed" domain by another user.
> 
> I can forward a link to this issue to the domain owner, though.

That would be great, thanks.
I know Google just acts with no sense.

**Comment by ThomasWaldmann** [comment]
Domain owner is aware of the issue now.

**Comment by githubtefo** [comment]
Today it was back to normal. Thanks @ThomasWaldmann !

**Comment by githubtefo** [comment]
The domain is consider a deceptive site again.
@ThomasWaldmann, could you share the contact of the owner of the domain in order to suggest him/her/them to include the domain in the public suffixes list?

**Comment by ThomasWaldmann** [comment]
i wrote him an email and suggested to provide direct contact info.

**Comment by TheGr8Wonder** [comment]
https://github.com/publicsuffix/list/pull/900

**Comment by githubtefo** [comment]
Great! Now my subdomain.awsmppl.com is not considered a Deceptive site anymore!
Thanks all!
Best.-
