### ISSUE TITLE
Disable function.

### ISSUE THREAD

**Issue by adrienb4** [nsupdate-info/nsupdate.info#438]
Hi :)

Is it possible to easily disable the **register** function in hosted nsupdate Django project ?

Thank you from France

**Comment by ThomasWaldmann** [comment]
django-registration-redux is what we use for registration - did you check its docs?

**Comment by adrienb4** [comment]
REGISTRATION_OPEN = False 
Thank you ;)

**Comment by ThomasWaldmann** [comment]
Fixed.
