### ISSUE TITLE
Allow services updates without RFC2136

### ISSUE THREAD

**Issue by lkraider** [nsupdate-info/nsupdate.info#450]
So this is a question for the project: would it make sense to allow enabling only the dyndns2 service update functionality for hosts on domains that don't support the RFC2136?

I feel most of the infrastructure is there to support this, and I even started building a custom update service (I have some domain providers that don't support dyndns2 protocol nor RFC2136).

As the system is right now, the RFC method is first class citizen, and the dyndns2 service is ran just after the update worked and mostly has no feedback for the user.

But both methods could be abstracted into a general interface, with the same error treating and retry functionality.

So I am asking: Do you think this makes sense for this project?

**Comment by ThomasWaldmann** [comment]
Well, currently it all revolves around the `Host` object (which represents some `hostname.nsupdate.info` host), so having that without actually updating the dns for that host would be strange.

But I get your idea. There could be a somehow unnamed / anon object for a host that has a list of updaters:
- for one or more hostnames on rfc2136 nameservers
- for one or more hostnames on dyndns services

That would be a more symmetric approach, but require a quite big internal restructuring + a DB migration procedure.

So while that would have been a nicer architecture to start from, I am not convinced that it is worth all the required work to migrate to that now.

**Comment by lkraider** [comment]
Thanks for the response! I'll close this issue for now.
