### ISSUE TITLE
Unable to update nameserver IP of existing Domain

### ISSUE THREAD

**Issue by elnappo** [nsupdate-info/nsupdate.info#457]
The update fails because [check_domain(domain)](https://github.com/nsupdate-info/nsupdate.info/blob/4581f90f2d9bbb7a05e968a912c56692113bc4e8/src/nsupdate/main/dnstools.py#L108) uses the old nameserver IP which is in some cases not available anymore and therefore the check fails.

**Comment by ThomasWaldmann** [comment]
Fixed by #492.
