### ISSUE TITLE
nerdpol.ovh hosts dont update even on the web interface

### ISSUE THREAD

**Issue by IvanTurgenev** [nsupdate-info/nsupdate.info#461]
it say dnserror on web and ddlclient logs
but only on existing nerdpol hosts this happens

**Comment by IvanTurgenev** [comment]
tried deleting and recreating but now  Name server unavailable.  :(

**Comment by ThomasWaldmann** [comment]
@elnappo ^^^

**Comment by elnappo** [comment]
I had to move the main name server for nerdpol.ovh to a new host. It appears to not yet work flawlessly. I'm working on it. For the meantime a restart of Bind seams to fix the problem but the root cause is still unknown. Sorry for any interruptions!

**Comment by elnappo** [comment]
The problem is not yet solved. For some reasons the Bind name server responsible for nerdpol.ovh stops accepting TCP connection on port 53 after some time. Therefore nsupdate.info can't send updates to it.

**Comment by ThomasWaldmann** [comment]
guess this is long solved (or solved after transfering the zone to ns*.thinkmo.de).
