### ISSUE TITLE
Social Oauth logins broken?

### ISSUE THREAD

**Issue by kellytrinh** [nsupdate-info/nsupdate.info#465]
2020_06_21_1822  (UTC + 8) --- the Oauth login seems broken?  Tried the usual login via google and got "500 unavailable"

Tried also github (tied to same email but maybe it setups up as new account; either way testing) - also get "500 unavailable" error

**Comment by ThomasWaldmann** [comment]
some updated python packages needed new database fields and I forgot to run the database migration...

can you try again now?

**Comment by ThomasWaldmann** [comment]
i tested github (works), the rest needs testing.

**Comment by kellytrinh** [comment]
Confirmed that google works.
