### ISSUE TITLE
Question: Sub-subdomain hosts without having to add each subdomain as availiable domain first?

### ISSUE THREAD

**Issue by abclution** [nsupdate-info/nsupdate.info#467]
Hi @ThomasWaldmann , long time no chat! Hope you are safe and healthy! Finally getting some time to play with nsupdate again.. 👍 

On to my question. Sorry, not really sure what it is called, let me explain.

I have added a dyn capable domain, greatdomain.com
The interface lets me add a host,  xxxx.greatdomain.com.
I would like to add a host,  yyyy.xxxx.greatdomain.com, 
without having to first add xxxx.greatdomain.com as a separate dynamic capable domain, first.

If I try to create yyyy.xxxx.greatdomain.com without adding xxxx.greatdomain.com as a domain first I get this error.

>Invalid host name: only "a-z", "0-9" and "-" is allowed

As far as I can tell, I can dynamically create these sub.sub.domain.com through the bind nsupdate as it just gets filed under the primary domain zone.

I can accept there may be reasons for this, but it sure would be helpful to know what they are for my own understanding?

Thanks!

**Comment by ThomasWaldmann** [comment]
The software is built with the assumption that there exists a dynamic domain (llike `nsupdate.info`) and that there are hosts added / remove from that domain.

Introducing subdomain levels in between could have unwanted consequences and maybe even bad security consequences, so this is no easy change.

E.g. if one user only adds `foo.bar` and another user adds `bar` to the same base domain.
