### ISSUE TITLE
IPv6 address updater does not handle IPv6 prefix string provided by Fritzbox DynDNS updater

### ISSUE THREAD

**Issue by nanosonde** [nsupdate-info/nsupdate.info#470]
I am using the following update URLs in the Fritzbox UI (v7.21 FB7590):

```
https://ipv4.nsupdate.info/nic/update 
https://ipv6.nsupdate.info/nic/update?myip=<ip6lanprefix>
```

The IPv6 prefix that is sent by the FB updater leads to following error:
`received bad ip address: '2a02:908:1200:1234::/64'`

Looking at the code, it seems that check_ip() does not recognize this as an ip address.

**Comment by ThomasWaldmann** [comment]
iiirc it expects an ip address not address-prefix/netmask.

**Comment by ThomasWaldmann** [comment]
code is deployed on nsupdate.info - try it!
