### ISSUE TITLE
Feature Request: Allow specification of ports

### ISSUE THREAD

**Issue by BerriJ** [nsupdate-info/nsupdate.info#474]
Hi there,
I have a couple of services running on my home network and I want to expose them. However, I only have 1 public IP address. I set up DynDNS using nsupdate.info (with my FritzBox) which works flawlessly. 
I can tell my router to redirect queries to specific devices depending on the port. However, I couldn't find any way to specify the port in the nsupdate settings. Is there a way to do so?
If not, it may be beneficial to implement such a feature. Or is there a workaround for this scenario?

Thanks in advance
BerriJ

**Comment by ThomasWaldmann** [comment]
DNS is a service to resolve names to IP addresses (or, via reverse DNS entries, IP addresses to names).

Ports are completely unrelated to this, so this "feature" does not make sense.

What you usually can do on the router is to forward some external port to an internal ip and port - that's all you need!

If you have multiple internal hosts offering the same service (e.g. multiple hosts with ssh on port 22), what one usually does is to use multiple external ports (e.g. 22, 2201, 2202, ... 2222) and then forward to the different internal machines depending on the external port.

**Comment by BerriJ** [comment]
Thank you very much for your timely response. I understand what you are saying about DNS and the router functionality of Port forwarding. 
However, what would I need to forward different custom Subdomains to different internal IPs? For example:

cloud.example.com >123.456.678:8080
helpdesk.example.com > 123.456.678:9090

Of course one could manually add the port behind the custom domain. However, using Subdomains would be more elegant I think.
