### ISSUE TITLE
nerdpol.ovh is down and not updating the IP

### ISSUE THREAD

**Issue by jkuj6** [nsupdate-info/nsupdate.info#475]
Have only recently noticed that nerdpol.ovh is down and not updating anything.  I also see that it says "unavailable" under "Overview".

Is this going to be fixed?  whats happening here?

Its kinda urgent, if it cant be fixed, please let people know so that they change to alternatives.

**Comment by ThomasWaldmann** [comment]
The general advice if a specific domain is down is to contact the DNS administrator.
Usually they have added (or should add) a contact address in the comment of the domain record on nsupdate.info web UI.

In case of nerdpol.ovh, this is @elnappo, let's see if he reads it here.

**Comment by elnappo** [comment]
Should be fixed now, sorry for the interruptions!
