### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by lonix1** [nsupdate-info/nsupdate.info#480]
Hello friends, excited to find this project as it fills a real need. :grinning:

But also surprised there's no official docker image. :cry: Haven't done python in years, so getting it to work isn't easy.

Does anyone have a working `Dockerfile` to share? Would be really appreciated, and I'll contribute my updates/tweaks.

**Comment by ThomasWaldmann** [comment]
I personally don't use docker, but if someone else does I suggest making a github project of it (with own issue tracker and docs) and then link to that from here.

**Comment by lonix1** [comment]
Ok

If anyone else reads this please post your Dockerfile? I'll contribute my tweaks for others to benefit.

**Comment by borekon** [comment]
> Ok
> 
> If anyone else reads this please post your Dockerfile? I'll contribute my tweaks for others to benefit.

Here's a dockerfile

**Comment by borekon** [comment]
> > Here's a dockerfile
> 
> :) ?

edited, sorry
