### ISSUE TITLE
can't use on android pie

### ISSUE THREAD

**Issue by cubetronic** [nsupdate-info/nsupdate.info#484]
an ip like 172.58.43.8 won't work

android pie requires a hostname to set up private dns

**Comment by ThomasWaldmann** [comment]
please be more verbose, i did not understand what your issue is.

**Comment by ThomasWaldmann** [comment]
https://en.wikipedia.org/wiki/Private_network just as a note for later: the mentioned IP is **not** a private network ip.

**Comment by cubetronic** [comment]
![Screenshot_20210605-144506_Settings](https://user-images.githubusercontent.com/11820866/120906257-af6d1180-c60c-11eb-9666-54f01881d672.png)

nsupdate.info shows 172.58.43.179 as if that's all i need to start using it. normally that would work, but android pie is fubar because google is evil, so it won't allow that. i need some android™ pie™ compatible hostname string. do you have one of those?

**Comment by ThomasWaldmann** [comment]
nsupdate.info is a **dyndns provider**, that's something completely different.
