### ISSUE TITLE
Unauthorized PayPal Use

### ISSUE THREAD

**Issue by 49-73** [nsupdate-info/nsupdate.info#491]
Received a suspicious PayPal Receipt for a payment I did not make.
If you select "CANCEL THIS PAYMENT" the link goes to; https://www.pertempuranmedanperangdisini33.nerdpol.ovh/

PayPal has no record of the listed transaction ID listing it as "INVALID".
So, the email has been forwarded to PayPal Resolution Center.
Do Not Click Any Hyperlink on this type of email. 
Oh, and it is not 10:24 PM anywhere in the USA yet on receipt.
You sent a payment of $27.98 USD
--

</body>
</html>You sent a payment of $27.98 USD

Thanks for using PayPal. To see the full transaction details, log in to your PayPal account. Keep in mind, it may take a few moments for this transaction to appear.

Transaction ID
[O-2677085861]()

Transaction date
Wed, April 06, 2022 10:24 PM

**Comment by ThomasWaldmann** [comment]
Thanks for reporting this.

I already received an abuse report for that dyndns host from another source.
I removed the abusive dyndns user and also deleted+blacklisted the hostname.

Thus, all done from our side.
