### ISSUE TITLE
CSRF verification failure

### ISSUE THREAD

**Issue by Chinarro** [nsupdate-info/nsupdate.info#493]
Hi,
Whenever I try loging in with my local account at your website, I get the following error text:

```
Referer checking failed - no Referer.

CSRF verification failure.

Either you are trying to access this site in 'unusual' ways (then please stop doing that), or
you found an issue in the code (then please file an issue for this and tell how you got here).
```
I've tried reaching the login form from the main page link and writing the full address on the navigation bar( https://www.nsupdate.info/accounts/login/) with the same result.
Thanks in advance

**Comment by ThomasWaldmann** [comment]
Maybe try a different browser, empty the cache. Also, do not use the "back" button of the browser.

I just tried with Safari and Brave browser and could not reproduce the issue. Logging in with a local account via the "Log in" link on the main page worked as expected.

**Comment by ThomasWaldmann** [comment]
In case you use some "security software" that is intercepting the data flow between the internet and your browser (like some virus scanners do), please try disabling it while you try to log in.

**Comment by Chinarro** [comment]
Hi,
Just tried Firefox and is working flawlessly.
Sorry for not testing it in advance and thanks for your quick answer.
