### ISSUE TITLE
Google OAuth Login is failing

### ISSUE THREAD

**Issue by Maeur1** [nsupdate-info/nsupdate.info#494]
When attempting to login with a Google Account, it appears to return an error page: 

![image](https://user-images.githubusercontent.com/1088281/174476512-e5ddf5b8-6ceb-4400-b08f-bdc3bcada425.png)

Unsure what this message means but it also means that I am unable to login to my original account and check on my domains. Is there something I can do to login using Google OAuth? 

Thanks!

**Comment by ThomasWaldmann** [comment]
Login with external accounts is currently disable due to abuse. You can still log in using a local account.

**Comment by Maeur1** [comment]
Ahhh is there a way to recover domains which were linked to the old o-auth login based account? Its not a big deal but would be interesting if there was some way to bring it.

**Comment by ThomasWaldmann** [comment]
You can write me an email to info @ nsupdate.info with your account details (username, hostname(s)) and I can try if I can add a local account / password.
