### ISSUE TITLE
Can’t login with google-oauth2 anymore

### ISSUE THREAD

**Issue by avibrazil** [nsupdate-info/nsupdate.info#499]
I used this auth methods for years.
Now it stopped working since a long time. Google says “invalid client” in the beginning of the auth process.

I also tried to reset password for same e-mail address used with google-auth2, in an attempt to use regular login. But no success. I never get an e-mail message with reset instructions.

Any update when it is going to be available again for login?

**Comment by ThomasWaldmann** [comment]
see #496.

if you do not get our emails, you've to talk to your email provider, usually it is because they reject our emails.
