### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by nornaro** [nsupdate-info/nsupdate.info#502]
Hi!

Cannot update any of my addresses (for quite some time now) as none of the login options work anymore.

github: err 404
Google, twitter, bitbucket: err 500

**Comment by ThomasWaldmann** [comment]
https://github.com/nsupdate-info/nsupdate.info/issues/496#issuecomment-1187319496 see there.

**Comment by nornaro** [comment]
My mistake, wrote email, and waiting for response.
