### ISSUE TITLE
logo needed

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#78]
for some purposes, it would be nice to have a good-looking logo, e.g. some social sites like to show some picture (and some even show a not-so-nice one if you don't provide one).

it should also be evaluated where that logo fits best into the userinterface of the software.

should be made in svg and we also need some pixel renderings of it in misc. sizes (including a new favicon).

so, if you have some artistic skills, help! :)

**Comment by mirzazulfan** [comment]
Hi @ThomasWaldmann i've designed a logo for your your project. If you need something else or change it, i'll fix it. Waiting you feedback.
![nsupdate](https://user-images.githubusercontent.com/36124339/55527998-89aeef80-56c5-11e9-8d6c-a323f587b145.png)

**Comment by ThomasWaldmann** [comment]
Looks pretty, thanks!

Just in case someone is asking: what does it show / what is the idea behind it?

**Comment by mirzazulfan** [comment]
Thanks for your response. I combine the server icon and update. and make the server icon form the initial letter 'ns'. if you need anything else I will make it.

**Comment by ThomasWaldmann** [comment]
@elnappo can you do a PR adding the logo?

**Comment by mirzazulfan** [comment]
@ThomasWaldmann what color do you prefer?

**Comment by ThomasWaldmann** [comment]
From the ones shown above, the blue/white one seems to be most appealing to me.

OTOH, the nsupdate.info site is currently a rather black/grey dull thing, so not sure what's best for it and whether we can make it more pretty in future.

A minor issue with the text: `nsupdate` is the name of a command line tool to update a nameserver (which we do not even use internally).

So if we want to point out the difference of our software / service to that tool, guess we must talk about `nsupdate.info`.

**Comment by mirzazulfan** [comment]
Blue and white look good. If you like it, I'll send all files and create a pull request if needed.
![mockup](https://user-images.githubusercontent.com/36124339/55671869-c8f46080-58be-11e9-88ff-3611b822b54f.png)

**Comment by ThomasWaldmann** [comment]
@elnappo what do you think?

**Comment by elnappo** [comment]
I really like the proposed logo :) Regarding the color, we should chose the color of the website based on the logo not the other way around. But I like your last proposal @mirzazulfan :)

**Comment by ThomasWaldmann** [comment]
ok, so we'll go with the blue one. :-)

@mirzazulfan when doing the PR, it would be great if you could specifically note that your works are released under the same license as the rest of the project (BSD 3-clause).

i sometimes had the case in other projects where somebody wondered 10y later where all the icons came from and whether they are legally used.

**Comment by mirzazulfan** [comment]
I don't really understand how to make a license, can you make it? I've created a pr #419 and you can download all editables files [here](https://drive.google.com/drive/folders/12TygV_t9vNedVA5zXNcujEN1111zXpSE) , If you need anything change in the future, dont hesitate to cantact me. Thanks guys :) Best regard!

**Comment by ThomasWaldmann** [comment]
You just need to say in your commit comment "i created these logos myself and license them under the same license as the nsupdate.info project's license".

This is somehow the default assumption when someone contributes stuff via a PR, but in my experience, graphics seems to raise suspicions in people looking at licensing compliance / (c) issues.

**Comment by ThomasWaldmann** [comment]
fixed by #431, thanks to @mirzazulfan and @elnappo!

**Comment by ThomasWaldmann** [comment]
live on https://www.nsupdate.info/ now! :-)
